apiVersion: v1
kind: Namespace
metadata:
  name: blackbox
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: blackbox
  namespace: blackbox
spec:
  interval: 10m
  url: https://prometheus-community.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: blackbox
  namespace: blackbox
spec:
  chart:
    spec:
      chart: prometheus-blackbox-exporter
      version: '8.4.0'
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: blackbox
  interval: 1m0s
  values:
    config:
      modules:
        http_2xx:
          prober: http
          timeout: 5s
          http:
            valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
            follow_redirects: true
            preferred_ip_protocol: "ip4"
        https_2xx:
          prober: http
          timeout: 5s
          http:
            method: GET
            fail_if_ssl: false
            fail_if_not_ssl: true
            valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
            valid_status_codes: [200]
            no_follow_redirects: false
            preferred_ip_protocol: "ip4"
    ingress:
      enabled: false
