apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: helm-charts
  namespace: default
spec:
  interval: 1m0s
  path: ./helm-charts
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
