apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: grafana
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./apps/grafana
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: gitops
  targetNamespace: grafana
  timeout: 3m0s
  wait: true
