apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prometheus
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./apps/prometheus
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: gitops
  targetNamespace: prometheus
  timeout: 3m0s
  wait: true
