apiVersion: v1
kind: Namespace
metadata:
  name: prometheus
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: prometheus
  namespace: prometheus
spec:
  interval: 60m
  url: https://grafana.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: prometheus
spec:
  interval: 5m
  chart:
    spec:
      chart: prometheus
      version: '25.4.0'
      sourceRef:
        kind: HelmRepository
        name: prometheus
        namespace: prometheus
      interval: 1m
